### ISSUE TITLE
Make more safer type and code modernizing

### ISSUE THREAD

**Issue by zeriyoshi** [colopl/laravel-spanner#101]
Support for PHP 8.1 , Laravel 10 and below was discontinued in version 5.0.

This is a good opportunity to clean up your code. I make the following suggestions

- [ ] Strict the types for the extent that it does not affect Laravel. (#102)
- [ ] Use a new, more readable syntax (#102)
- [ ] Implement an auto-formatting tool ~(#100)~
- [ ] implement stricter static inspections of future code ~(#100)~
